# Generated by Django 5.2.15 on 2026-07-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'priority', '-created_at']},
        ),
    ]
